name: ci

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Run Tests with SW
        run: yarn test:ember-include
      - name: Run Tests without SW
        run: yarn test:ember-exclude

  test-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        # Keep this in sync with config/ember-try.js
        ember:
          [
            ember-lts-3.20,
            ember-release,
            ember-canary,
            embroider-optimized,
            ember-release-no-sw,
            embroider-no-sw,
          ]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test-matrix ${{ matrix.ember }}
